name: Python Publish

on:
  push:
    branches:
      - main  # Trigger the workflow only on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Set the version of Python to use

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from your requirements file

    # Run tests (if you have tests, otherwise skip this step)
    - name: Run tests
      run: |
        # Replace this with your test command if applicable
        pytest  # Assuming you use pytest for tests

    # Build and publish the package to PyPI (this assumes you're using setuptools)
    - name: Build and Publish to PyPI
      run: |
        python setup.py sdist bdist_wheel  # Build your package
        pip install twine  # Install twine if it's not already installed
        twine upload dist/*  # Upload to PyPI
      env:
        # These values should be added as Secrets in your GitHub repository
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

    # Optionally, notify on success
    - name: Notify Success
      if: success()
      run: echo "Successfully published the package to PyPI!"

    # Optionally, notify on failure
    - name: Notify Failure
      if: failure()
      run: echo "Failed to publish the package to PyPI."